/**
 * Script migrasi ringan: memastikan kolom tabel sesuai versi terbaru schema.
 * Idempotent — aman dijalankan berulang kali.
 * Jalankan: node src/scripts/migrate.js
 */
require('dotenv').config();
const { pool } = require('../config/db');

// Tabel yang dipastikan ada (CREATE TABLE IF NOT EXISTS)
const tables = [
  `CREATE TABLE IF NOT EXISTS settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`
];

// Perhatikan: kolom `is_active` TINYINT(1) MySQL → SMALLINT (0/1) PostgreSQL
const migrations = [
  {
    table: 'documents',
    column: 'document_date',
    ddl: 'ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_date DATE'
  },
  {
    table: 'documents',
    column: 'effective_date',
    ddl: 'ALTER TABLE documents ADD COLUMN IF NOT EXISTS effective_date DATE'
  },
  {
    table: 'documents',
    column: 'is_active',
    ddl: 'ALTER TABLE documents ADD COLUMN IF NOT EXISTS is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))'
  },
  {
    table: 'document_chunks',
    column: 'page_number',
    ddl: 'ALTER TABLE document_chunks ADD COLUMN IF NOT EXISTS page_number INT'
  },
  {
    table: 'document_chunks',
    column: 'section',
    ddl: 'ALTER TABLE document_chunks ADD COLUMN IF NOT EXISTS section VARCHAR(255)'
  }
];

const run = async () => {
  try {
    for (const ddl of tables) {
      await pool.query(ddl);
    }
    console.log('✅ Tabel dipastikan ada.');

    for (const m of migrations) {
      const [rows] = await pool.query(
        `SELECT COUNT(*) AS n FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = ? AND column_name = ?`,
        [m.table, m.column]
      );

      if (rows[0].n === 0) {
        await pool.query(m.ddl);
        console.log(`✅ Kolom ditambahkan: ${m.table}.${m.column}`);
      } else {
        console.log(`ℹ️ Kolom sudah ada: ${m.table}.${m.column}`);
      }
    }
    console.log('🎉 Migrasi selesai.');
  } catch (err) {
    console.error('❌ Gagal migrasi:', err.message);
    process.exitCode = 1;
  } finally {
    await pool.end();
  }
};

run();
