-- =====================================================================
-- BPOM AI — PostgreSQL Database Schema (hasil migrasi dari MySQL)
-- Database : bbpom_ai
--
-- Cara menjalankan:
--   1) Docker  : `docker compose up -d postgres`
--        → skema otomatis dibuat lewat /docker-entrypoint-initdb.d
--   2) Manual  : psql -U <user> -d bbpom_ai -f backend/sql/schema.pg.sql
--   3) Via app : npm run db:schema   (dari folder backend)
--
-- Pemetaan tipe MySQL → PostgreSQL:
--   INT AUTO_INCREMENT     → INT GENERATED BY DEFAULT AS IDENTITY
--   BIGINT AUTO_INCREMENT  → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   TINYINT(1) boolean 0/1 → SMALLINT + CHECK (0/1) — nilai tetap 0/1
--   ENUM(...)              → TEXT + CHECK
--   JSON                   → JSONB
--   LONGTEXT / TEXT        → TEXT
--   TIMESTAMP ON UPDATE    → trigger set_updated_at()
--
-- Semua pernyataan idempoten (aman dijalankan berulang).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. roles
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- 2. users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  nip VARCHAR(30),
  role_id INT NOT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  last_login TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id)
    REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);

-- ---------------------------------------------------------------------
-- 3. sources  (sumber referensi: URL, PDF, regulasi, dll)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sources (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  type TEXT NOT NULL DEFAULT 'url'
    CHECK (type IN ('url', 'pdf', 'docx', 'regulasi', 'lainnya')),
  url VARCHAR(500),
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- 4. document_categories
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS document_categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  parent_id INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_doc_cat_parent FOREIGN KEY (parent_id)
    REFERENCES document_categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT uq_document_categories_name UNIQUE (name)
);
CREATE INDEX IF NOT EXISTS idx_doc_cat_parent ON document_categories(parent_id);

-- ---------------------------------------------------------------------
-- 5. documents
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS documents (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category_id INT,
  source_id INT,
  file_path VARCHAR(500),
  file_type VARCHAR(50),
  uploaded_by INT,
  document_date DATE,
  effective_date DATE,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'uploaded', 'processing', 'ready', 'failed')),
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  metadata JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_documents_category FOREIGN KEY (category_id)
    REFERENCES document_categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_documents_source FOREIGN KEY (source_id)
    REFERENCES sources(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_documents_uploader FOREIGN KEY (uploaded_by)
    REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_documents_category ON documents(category_id);
CREATE INDEX IF NOT EXISTS idx_documents_source ON documents(source_id);
CREATE INDEX IF NOT EXISTS idx_documents_uploader ON documents(uploaded_by);

-- ---------------------------------------------------------------------
-- 6. document_chunks  (potongan teks untuk RAG / semantic search)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS document_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id INT NOT NULL,
  chunk_index INT NOT NULL,
  content TEXT NOT NULL,
  page_number INT,
  section VARCHAR(255),
  embedding JSONB,
  metadata JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chunks_document FOREIGN KEY (document_id)
    REFERENCES documents(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chunks_document ON document_chunks(document_id);
CREATE INDEX IF NOT EXISTS idx_chunks_document_index
  ON document_chunks(document_id, chunk_index);

-- ---------------------------------------------------------------------
-- 7. faq
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS faq (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category VARCHAR(100),
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- 8. chat_sessions
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_sessions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  title VARCHAR(255) NOT NULL DEFAULT 'Percakapan baru',
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'closed')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chat_sessions_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_user ON chat_sessions(user_id);

-- ---------------------------------------------------------------------
-- 9. chat_messages
--    Catatan: "role" adalah reserved word di PostgreSQL → harus di-quote.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INT NOT NULL,
  "role" TEXT NOT NULL CHECK ("role" IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  sources JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chat_messages_session FOREIGN KEY (session_id)
    REFERENCES chat_sessions(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id);

-- ---------------------------------------------------------------------
-- 10. ai_logs  (log pemakaian model AI)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  model VARCHAR(100),
  prompt TEXT,
  response TEXT,
  tokens_used INT,
  duration_ms INT,
  status TEXT NOT NULL DEFAULT 'success'
    CHECK (status IN ('success', 'failed')),
  error TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_logs_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ai_logs_user ON ai_logs(user_id);

-- ---------------------------------------------------------------------
-- 11. feedback
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feedback (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  message_id BIGINT,
  rating SMALLINT CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_feedback_message FOREIGN KEY (message_id)
    REFERENCES chat_messages(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_feedback_user ON feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_feedback_message ON feedback(message_id);

-- ---------------------------------------------------------------------
-- 12. settings  (konfigurasi runtime — mis. API key & model LLM)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- Trigger: menggantikan perilaku `ON UPDATE CURRENT_TIMESTAMP` MySQL
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_roles_updated_at ON roles;
CREATE TRIGGER trg_roles_updated_at BEFORE UPDATE ON roles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_sources_updated_at ON sources;
CREATE TRIGGER trg_sources_updated_at BEFORE UPDATE ON sources
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_document_categories_updated_at ON document_categories;
CREATE TRIGGER trg_document_categories_updated_at BEFORE UPDATE ON document_categories
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_documents_updated_at ON documents;
CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON documents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_faq_updated_at ON faq;
CREATE TRIGGER trg_faq_updated_at BEFORE UPDATE ON faq
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_chat_sessions_updated_at ON chat_sessions;
CREATE TRIGGER trg_chat_sessions_updated_at BEFORE UPDATE ON chat_sessions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_settings_updated_at ON settings;
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
